# Generated by Django 3.2.4 on 2021-10-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_products_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
    ]
