# Generated by Django 3.2.4 on 2021-10-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_product_name_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=16)),
                ('item_quantity', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_name', models.CharField(max_length=16)),
                ('phone_name', models.CharField(max_length=8)),
                ('Amount', models.BigIntegerField()),
            ],
        ),
    ]
