# Generated by Django 3.2.4 on 2021-10-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_order_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='Account_name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='payments',
            name='Amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='phone_name',
            field=models.CharField(max_length=15),
        ),
    ]
