# Generated by Django 3.2.4 on 2021-10-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20211029_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=16)),
                ('item_quantity', models.CharField(max_length=8)),
            ],
        ),
    ]
