# Generated by Django 3.2.4 on 2021-11-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cut_through_price',
        ),
    ]
